server:
  port: 0
spring:
  datasource:
    star:
      url: jdbc:mysql://localhost:3306/star?serverTimezone=UTC&useSSL=false
      username: root
      password: MAvx1Xq7
      driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com: TRACE
  file: spring-boot-logging.log