cusvar: local
server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_star
    username: root
    password: 12345678
    driverClassName: com.mysql.cj.jdbc.Driver
    initialSize: 1
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 3600000
    minEvictableIdleTimeMillis: 4000000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnReturn: false
    testOnBorrow: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
      #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall, log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.joruns.test.demo.dao
  configuration:
    map-underscore-to-camel-case: true
redis:
    host: 172.0.0.1
    password: 123456
    port: 6379
    timeout: 300000000 # 连接超时时间（毫秒）
    # 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 200
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0


